# Default Configuration
spring.profiles.active=dev
# H2 Console
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics,loggers
management.endpoint.health.show-details=always

# Module 10: Circuit Breaker Config
# Open Circuit after 50% failure rate (in last 5 calls)
resilience4j.circuitbreaker.instances.paymentService.sliding-window-size=5
resilience4j.circuitbreaker.instances.paymentService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paymentService.wait-duration-in-open-state=10000ms
resilience4j.circuitbreaker.instances.paymentService.permitted-number-of-calls-in-half-open-state=3

# Module 13: Rate Limiter Config
# Limit: 5 requests per 60 seconds
resilience4j.ratelimiter.instances.basic.limit-for-period=5
resilience4j.ratelimiter.instances.basic.limit-refresh-period=60s
resilience4j.ratelimiter.instances.basic.timeout-duration=0ms
