# DEV PROFILE
# ==========================================
# Database: H2 (In-Memory)
spring.datasource.url=jdbc:h2:mem:devdb
spring.h2.console.enabled=true

# Logging
logging.level.org.springframework.web=DEBUG

# Custom Business Config
app.environment.name=Development Implementation
app.feature.beta-enabled=true
